### ISSUE TITLE
SCSS 2 CSS Missing vendor prefixes and multiple lines with same style declaration 

### ISSUE THREAD

**Issue by BernhardBehrendt** [yeoman/generator-angular#920]
I've read in a previous issue (#389) that IE is not supportet lower 10 or 9 by angular.
That's ok but I just found out there are issues procesing e.g. following line:

``` scss
    .item{
        @include transform(rotate(180deg));
    }
```

My expected output is something like this (already validated by seting up a tescase using compass only):

``` css
    .item{
        -webkit-transform: rotate(180deg);
        -moz-transform: rotate(180deg);
        -ms-transform: rotate(180deg);
        transform: rotate(180deg);
    }
```

But when I had a look into sass compilers output I see the following output:

``` css
    .item{
        -webkit-transform: rotate(180deg);
       transform: rotate(180deg);
       -webkit-transform: rotate(180deg);
       transform: rotate(180deg);
       -webkit-transform: rotate(180deg);
       transform: rotate(180deg);
       -webkit-transform: rotate(180deg);
       transform: rotate(180deg);
    }
```

Then I've disabled autoprefixer task because making changes on it's config doesn't brought any change and then the output was:

``` css
    .item{
        transform: rotate(180deg);
        transform: rotate(180deg);
        transform: rotate(180deg); 
        transform: rotate(180deg);
    }
```

That's the output (and expected result) if I compile directly by compass:

``` css
    .item{   
        -moz-transform: rotate(180deg);
        -ms-transform: rotate(180deg);
        -webkit-transform: rotate(180deg);
        transform: rotate(180deg);
    }
```

What could be the reason fot that behavior?
I need the ms- vendor prefixes to target IE9.
